// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_service.proto

package com.amos.grpc.api.service;

public final class HelloServiceProto {
  private HelloServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023hello_service.proto\022\031com.amos.grpc.api" +
      ".service\032\031google/protobuf/any.proto\032\033goo" +
      "gle/protobuf/empty.proto\032\027model/hello_mo" +
      "del.proto2\376\001\n\014HelloService\022Y\n\010sayHello\022%" +
      ".com.amos.grpc.api.model.HelloRequest\032&." +
      "com.amos.grpc.api.model.HelloResponse\022]\n" +
      "\010register\022(.com.amos.grpc.api.model.Regi" +
      "sterRequest\032\'.com.amos.grpc.api.model.Co" +
      "mmonResponse\0224\n\004good\022\026.google.protobuf.E" +
      "mpty\032\024.google.protobuf.AnyB0\n\031com.amos.g" +
      "rpc.api.serviceB\021HelloServiceProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.amos.grpc.api.model.HelloModelProto.getDescriptor(),
        });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.amos.grpc.api.model.HelloModelProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
