// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/hello_model.proto

package com.amos.grpc.api.model;

public final class HelloModelProto {
  private HelloModelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amos_grpc_api_model_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amos_grpc_api_model_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amos_grpc_api_model_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amos_grpc_api_model_HelloResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amos_grpc_api_model_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amos_grpc_api_model_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amos_grpc_api_model_RegisterRequest_ExtInfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amos_grpc_api_model_RegisterRequest_ExtInfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amos_grpc_api_model_CommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amos_grpc_api_model_CommonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027model/hello_model.proto\022\027com.amos.grpc" +
      ".api.model\032\031google/protobuf/any.proto\"\034\n" +
      "\014HelloRequest\022\014\n\004name\030\001 \001(\t\" \n\rHelloResp" +
      "onse\022\017\n\007message\030\001 \001(\t\"\264\001\n\017RegisterReques" +
      "t\022\014\n\004name\030\001 \001(\t\022\016\n\006gender\030\002 \001(\t\022\013\n\003age\030\003" +
      " \001(\005\022F\n\007extInfo\030\004 \003(\01325.com.amos.grpc.ap" +
      "i.model.RegisterRequest.ExtInfoEntry\032.\n\014" +
      "ExtInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"S\n\016CommonResponse\022\014\n\004code\030\001 \001(\t\022\017\n\007" +
      "message\030\002 \001(\t\022\"\n\004body\030\003 \001(\0132\024.google.pro" +
      "tobuf.AnyB,\n\027com.amos.grpc.api.modelB\017He" +
      "lloModelProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_amos_grpc_api_model_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amos_grpc_api_model_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amos_grpc_api_model_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_amos_grpc_api_model_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_amos_grpc_api_model_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amos_grpc_api_model_HelloResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_amos_grpc_api_model_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_amos_grpc_api_model_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amos_grpc_api_model_RegisterRequest_descriptor,
        new java.lang.String[] { "Name", "Gender", "Age", "ExtInfo", });
    internal_static_com_amos_grpc_api_model_RegisterRequest_ExtInfoEntry_descriptor =
      internal_static_com_amos_grpc_api_model_RegisterRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_amos_grpc_api_model_RegisterRequest_ExtInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amos_grpc_api_model_RegisterRequest_ExtInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_amos_grpc_api_model_CommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_amos_grpc_api_model_CommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amos_grpc_api_model_CommonResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Body", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
