// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/hello_model.proto

package com.amos.grpc.api.model;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amos.grpc.api.model.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
