// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/hello_model.proto

package com.amos.grpc.api.model;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amos.grpc.api.model.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string gender = 2;</code>
   * @return The gender.
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 2;</code>
   * @return The bytes for gender.
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>int32 age = 3;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>map&lt;string, string&gt; extInfo = 4;</code>
   */
  int getExtInfoCount();
  /**
   * <code>map&lt;string, string&gt; extInfo = 4;</code>
   */
  boolean containsExtInfo(
      java.lang.String key);
  /**
   * Use {@link #getExtInfoMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExtInfo();
  /**
   * <code>map&lt;string, string&gt; extInfo = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtInfoMap();
  /**
   * <code>map&lt;string, string&gt; extInfo = 4;</code>
   */

  java.lang.String getExtInfoOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; extInfo = 4;</code>
   */

  java.lang.String getExtInfoOrThrow(
      java.lang.String key);
}
